# Operacoes com Matrizes

In [129]:
import numpy as np

In [130]:
matrizA = np.array([[2,-3],
                   [4,-6],
                   [6,9]])
matrizA

array([[ 2, -3],
       [ 4, -6],
       [ 6,  9]])

In [131]:
matrizB = np.array([[1,7],
                   [-4,4],
                   [5,-8]])
matrizB

array([[ 1,  7],
       [-4,  4],
       [ 5, -8]])

In [132]:
matrizC = np.array([[7,4],
                    [8,3],
                    [4,2]])
matrizC

array([[7, 4],
       [8, 3],
       [4, 2]])

## Formato de Matrizes
### funcao shape (linhas,colunas)

In [133]:
matrizA.shape

(3, 2)

In [134]:
matrizB.shape

(3, 2)

In [135]:
matrizC.shape

(3, 2)

## Soma de Matrizes

In [136]:
somaAB = matrizA + matrizB
somaAB

array([[ 3,  4],
       [ 0, -2],
       [11,  1]])

In [137]:
somaAC = matrizA + matrizC
somaAC

array([[ 9,  1],
       [12, -3],
       [10, 11]])

In [138]:
somaBC = matrizB + matrizC
somaBC

array([[ 8, 11],
       [ 4,  7],
       [ 9, -6]])

## Subtracao de Matrizes

In [139]:
subAB = matrizA - matrizB
subAB

array([[  1, -10],
       [  8, -10],
       [  1,  17]])

In [140]:
subBA = matrizB - matrizA
subBA

array([[ -1,  10],
       [ -8,  10],
       [ -1, -17]])

In [141]:
subAC = matrizA - matrizC
subAC

array([[-5, -7],
       [-4, -9],
       [ 2,  7]])

In [142]:
subCA = matrizC - matrizA
subCA

array([[ 5,  7],
       [ 4,  9],
       [-2, -7]])

In [143]:
subCB = matrizC - matrizB
subCB

array([[ 6, -3],
       [12, -1],
       [-1, 10]])

In [144]:
subBC = matrizB - matrizC
subBC

array([[ -6,   3],
       [-12,   1],
       [  1, -10]])

## Multiplicacao por Escalar

In [145]:
multiA2 = matrizA * 2
multiA2

array([[  4,  -6],
       [  8, -12],
       [ 12,  18]])

In [146]:
multiBm3 = matrizB * -3
multiBm3

array([[ -3, -21],
       [ 12, -12],
       [-15,  24]])

In [147]:
multiC13 = matrizC * 13
multiC13

array([[ 91,  52],
       [104,  39],
       [ 52,  26]])

## Multiplicacao de Matrizes
### Para que haja uma multiplicacao de matrizes, o numero de colunas de uma matriz deve ser igual o numero de linhas da outra matriz

In [148]:
matrizD = np.array([[7,8,0],
                   [10,5,-2]])
matrizD

array([[ 7,  8,  0],
       [10,  5, -2]])

In [149]:
multCD = np.dot(matrizC,matrizD)
multCD

array([[89, 76, -8],
       [86, 79, -6],
       [48, 42, -4]])

In [150]:
multDC = np.dot(matrizD,matrizC)
multDC

array([[113,  52],
       [102,  51]])

## Matriz Inversa
### Uma matriz quadrada A eh inversivel se existe a matriz B tal que :
### A.B = B.A = I

In [151]:
matrizIA = np.array([[2,5],[1,3]])
matrizIA

array([[2, 5],
       [1, 3]])

In [152]:
matrizIB = np.array([[3,-5],[-1,2]])
matrizIB

array([[ 3, -5],
       [-1,  2]])

In [153]:
matrizInv1 = np.dot(matrizIA,matrizIB)
matrizInv1

array([[1, 0],
       [0, 1]])

In [154]:
matrizInv2 = np.dot(matrizIB,matrizIA)
matrizInv2

array([[1, 0],
       [0, 1]])