In [18]:
import numpy as np
import scipy as sp
from scipy import linalg

In [3]:
matrizA = np.array([[2,5],[1,3]])
matrizA

array([[2, 5],
       [1, 3]])

In [4]:
matrizB = np.array([[3,-5],[-1,2]])
matrizB

array([[ 3, -5],
       [-1,  2]])

In [5]:
mult = np.dot(matrizA,matrizB)
mult

array([[1, 0],
       [0, 1]])

## Matriz Inversa

In [7]:
matriz_invA = np.linalg.inv(matrizA)
matriz_invA

array([[ 3., -5.],
       [-1.,  2.]])

In [9]:
matriz_invB = np.linalg.inv(matrizB)
matriz_invB

array([[2., 5.],
       [1., 3.]])

In [10]:
matrizC = np.array([[-11,2,2],[-4,0,1],[6,-1,-1]])
matrizC

array([[-11,   2,   2],
       [ -4,   0,   1],
       [  6,  -1,  -1]])

In [14]:
matrizC_Invc = np.linalg.inv(matrizC)
matrizC_Invc

array([[ 1.00000000e+00,  2.01858732e-16,  2.00000000e+00],
       [ 2.00000000e+00, -1.00000000e+00,  3.00000000e+00],
       [ 4.00000000e+00,  1.00000000e+00,  8.00000000e+00]])

## Determinante

In [15]:
matrizE = np.array([[1,3,2],[4,2,4],[3,1,5]])
matrizE

array([[1, 3, 2],
       [4, 2, 4],
       [3, 1, 5]])

In [16]:
detE = np.linalg.det(matrizE)
detE

-22.000000000000004

In [19]:
detscE = sp.linalg.det(matrizE)
detscE

-22.0

In [20]:
matrizF = np.array([[2,4],[3,8]])
matrizF

array([[2, 4],
       [3, 8]])

In [22]:
detF1 = np.linalg.det(matrizF)
detF1

3.999999999999999

In [23]:
detF1 = sp.linalg.det(matrizF)
detF1

4.0

In [24]:
matrizH = np.array([[1,3,0,-2,1],
                    [4,2,4,5,4],
                    [0,1,5,-3,2],
                    [-2,3,1,0,7],
                    [0,1,9,3,2]])
matrizH

array([[ 1,  3,  0, -2,  1],
       [ 4,  2,  4,  5,  4],
       [ 0,  1,  5, -3,  2],
       [-2,  3,  1,  0,  7],
       [ 0,  1,  9,  3,  2]])

In [25]:
detH = np.linalg.det(matrizH)
detH

3591.9999999999986

In [26]:
detH = sp.linalg.det(matrizH)
detH

3592.000000000001